### ISSUE TITLE
can build on linux but...

### ISSUE THREAD

**Issue by alexmyczko** [pete-gordon/planet-hively#2]
./planethively
Cannot open file
Couldn't load 'tunes/syphus-sweeties.hvl'!!!11111one

i can see that tune as c header include file in embedded_tunes.

**Comment by pete-gordon** [comment]
Most ports expect the tunes to be in the filesystem separate to the executable. The embedded tunes were mainly for console ports where there might not be a filesystem.

You either need to change the build flags to enable the embedded tunes, or grab one of the binary releases from the download page (http://www.hivelytracker.co.uk/planethively/), and copy your new executable over the one from the release.

**Comment by alexmyczko** [comment]
Indeed, adding CFLAGS += -D__EMBED_TUNES__ works.
